const customers = [
  { id:'CUS-0001', company:'株式会社さくら市場', type:'食品スーパー', contact:'営業ご担当者', phone:'03-0000-1101', email:'sales@sakura-market.example.test', products:'ねぎとろ・まぐろ切落し', status:'取引中', statusClass:'active', address:'東京都中央区晴海1-2-3', department:'鮮魚部', notes:'週末の鮮魚フェア向けに定番商品を継続提案中。', followUps:[{date:'2026/09/08',method:'電話',owner:'営業担当',content:'秋のまぐろフェアの販売計画を確認しました。',feedback:'ねぎとろの増量規格に関心あり。',nextDate:'2026/09/18',action:'規格提案書を送付'}]},
  { id:'CUS-0002', company:'フードリンクダイニング株式会社', type:'外食チェーン', contact:'購買ご担当者', phone:'03-0000-2202', email:'buying@foodlink-dining.example.test', products:'まぐろたたき・漬けまぐろ', status:'取引中', statusClass:'active', address:'東京都新宿区西新宿4-5-6', department:'商品調達部', notes:'丼業態の季節メニュー向けに新商品の採用を検討中。', followUps:[{date:'2026/09/04',method:'メール',owner:'営業担当',content:'漬けまぐろの規格書と試食案内を送付しました。',feedback:'店舗テストの日程を調整中。',nextDate:'2026/09/22',action:'試食結果を確認'}]},
  { id:'CUS-0003', company:'東浜フーズ流通株式会社', type:'食品卸', contact:'仕入ご担当者', phone:'045-0000-3303', email:'procurement@tohama-foods.example.test', products:'赤身柵・中おち風', status:'商談中', statusClass:'pending', address:'神奈川県横浜市港北区新羽町7-8-9', department:'水産営業課', notes:'首都圏量販店向けの共同企画を商談中。', followUps:[{date:'2026/09/10',method:'オンライン会議',owner:'営業担当',content:'冷凍まぐろシリーズの物流条件を打合せしました。',feedback:'配送ロットを社内確認するとのことです。',nextDate:'2026/09/25',action:'物流条件の回答'}]},
  { id:'CUS-0004', company:'みなと惣菜製造株式会社', type:'食品メーカー', contact:'開発ご担当者', phone:'052-0000-4404', email:'development@minato-deli.example.test', products:'まぐろたたき・中おち風', status:'取引中', statusClass:'active', address:'愛知県名古屋市港区潮見町10-11', department:'商品開発室', notes:'海鮮惣菜用の原料として定期採用中。', followUps:[{date:'2026/08/29',method:'訪問',owner:'営業担当',content:'年末向け惣菜の試作品を確認しました。',feedback:'原料の粒度を評価いただきました。',nextDate:'2026/09/20',action:'年末数量を確認'}]},
  { id:'CUS-0005', company:'北辰グロサリー合同会社', type:'食品卸', contact:'営業ご担当者', phone:'011-0000-5505', email:'sales@hokushin-grocery.example.test', products:'まぐろ切落し', status:'休眠', statusClass:'inactive', address:'北海道札幌市北区北十条西12-13', department:'冷凍食品部', notes:'現在は取引休止中。季節商材のご案内を予定。', followUps:[{date:'2026/07/15',method:'メール',owner:'営業担当',content:'秋冬カタログを送付しました。',feedback:'返信待ち。',nextDate:'2026/10/15',action:'取扱状況を確認'}]}
];
const products = [
  {code:'KST-MG-001',name:'まぐろたたき 500g',category:'まぐろ加工品',ingredients:'キハダマグロ、植物油脂、pH調整剤',weight:'500g',packing:'袋',case:'20袋',expiry:'冷凍で製造日より365日',storage:'-18℃以下で保存',price:1480,description:'丼・軍艦巻きに使いやすい、なめらかな食感のまぐろたたきです。',notes:'解凍後は当日中にご使用ください。'},
  {code:'KST-NG-002',name:'ねぎとろ 300g',category:'まぐろ加工品',ingredients:'キハダマグロ、メバチマグロ、植物油脂',weight:'300g',packing:'袋',case:'30袋',expiry:'冷凍で製造日より365日',storage:'-18℃以下で保存',price:980,description:'小売・外食の使い切りに適した、粒感のあるねぎとろです。',notes:'わさび・ねぎは付属しません。'},
  {code:'KST-AK-003',name:'まぐろ赤身柵 700g',category:'冷凍まぐろ',ingredients:'メバチマグロ',weight:'700g前後',packing:'真空パック',case:'10柵',expiry:'冷凍で製造日より730日',storage:'-18℃以下で保存',price:2380,description:'刺身、寿司に使いやすい、色目の良い赤身柵です。',notes:'重量には個体差があります。'},
  {code:'KST-ZK-004',name:'漬けまぐろ切落し 200g',category:'味付けまぐろ',ingredients:'キハダマグロ、しょうゆ、みりん、砂糖',weight:'200g',packing:'袋',case:'40袋',expiry:'冷凍で製造日より365日',storage:'-18℃以下で保存',price:720,description:'特製たれで漬け込んだ、丼メニュー向けの切落しです。',notes:'原材料の一部に小麦・大豆を含みます。'},
  {code:'KST-NA-005',name:'まぐろ中おち風 500g',category:'まぐろ加工品',ingredients:'キハダマグロ、植物油脂、魚油',weight:'500g',packing:'袋',case:'20袋',expiry:'冷凍で製造日より365日',storage:'-18℃以下で保存',price:1280,description:'巻物や惣菜に便利な、コクのある中おち風商品です。',notes:'加熱用ではありません。'}
];
let quotations = [
  {no:'Q-2026-0418',date:'2026-09-03',customerId:'CUS-0001',productCode:'KST-NG-002',qty:60,price:980,notes:'秋の鮮魚フェア向け',status:'提出済み'},
  {no:'Q-2026-0386',date:'2026-08-12',customerId:'CUS-0002',productCode:'KST-ZK-004',qty:120,price:720,notes:'店舗テスト用',status:'商談中'},
  {no:'Q-2026-0291',date:'2026-06-18',customerId:'CUS-0003',productCode:'KST-AK-003',qty:50,price:2380,notes:'首都圏量販店向け',status:'受注'},
  {no:'Q-2026-0224',date:'2026-05-30',customerId:'CUS-0004',productCode:'KST-MG-001',qty:80,price:1480,notes:'夏季惣菜原料',status:'受注'}
];
let orders = [];
const byId = id => customers.find(c => c.id === id); const byCode = code => products.find(p => p.code === code);
const money = value => `¥${Number(value).toLocaleString('ja-JP')}`;
const formatDate = value => value ? value.replaceAll('-','/') : '—';
const currentDate = () => new Date().toISOString().slice(0, 10);
const badgeClass = status => ({'取引中':'active','提出済み':'sent','商談中':'pending','下書き':'draft','受注':'active','確認中':'pending','出荷準備中':'pending','出荷済み':'sent','キャンセル':'lost','失注':'lost','休眠':'inactive'})[status] || 'draft';
const badge = status => `<span class="status status-${badgeClass(status)}">${status}</span>`;
const renderCustomers = (items = customers) => { document.querySelector('#customer-table-body').innerHTML = items.map(c => `<tr><td>${c.id}</td><td class="company-name">${c.company}</td><td>${c.type}</td><td>${c.contact}</td><td>${c.phone}</td><td>${c.email}</td><td>${c.products}</td><td>${badge(c.status)}</td><td><button class="table-link" data-customer-id="${c.id}" type="button">詳細</button></td></tr>`).join(''); document.querySelector('#customer-count').textContent=`${items.length}件の顧客`; document.querySelector('#customer-empty').hidden=!!items.length; };
const renderProducts = (items = products) => { document.querySelector('#product-table-body').innerHTML=items.map(p=>`<tr data-product-code="${p.code}" tabindex="0"><td>${p.code}</td><td class="company-name">${p.name}</td><td>${p.category}</td><td>${p.weight}</td><td>${p.packing}</td><td>${p.case}</td><td>${p.storage}</td><td>${money(p.price)}</td><td class="description-cell">${p.description}</td></tr>`).join(''); document.querySelector('#product-count').textContent=`${items.length}件の商品`; };
const renderQuotations = (items = quotations) => { document.querySelector('#quotation-table-body').innerHTML=items.map(q=>{const c=byId(q.customerId),p=byCode(q.productCode),existing=orders.find(o=>o.quotationNo===q.no);const action=q.status==='受注' ? (existing ? `<span class="registered-label">受注登録済み<br><strong>${existing.no}</strong></span>` : `<button class="table-link" data-quotation-no="${q.no}" type="button">受注登録</button>`) : '—';return `<tr><td>${q.no}</td><td>${formatDate(q.date)}</td><td class="company-name">${c.company}</td><td>${p.name}</td><td>${q.qty}</td><td>${money(q.price)}</td><td>${money(q.qty*q.price)}</td><td>${q.notes || '—'}</td><td>${badge(q.status)}</td><td>${action}</td></tr>`}).join(''); document.querySelector('#quotation-count').textContent=`${items.length}件の見積`;document.querySelector('#quotation-empty').hidden=!!items.length; };
const renderOrders = (items = orders) => { document.querySelector('#order-table-body').innerHTML=items.map(o=>{const c=byId(o.customerId),p=byCode(o.productCode);return `<tr><td>${o.no}</td><td>${formatDate(o.date)}</td><td class="company-name">${c.company}</td><td>${p.name}</td><td>${o.qty}</td><td>${money(o.price)}</td><td>${money(o.qty*o.price)}</td><td>${formatDate(o.deliveryDate)}</td><td>${o.notes || '—'}</td><td>${o.quotationNo || '—'}</td><td>${badge(o.status)}</td></tr>`}).join(''); document.querySelector('#order-count').textContent=`${items.length}件の受注`;document.querySelector('#order-empty').hidden=!!items.length; };
function showView(view) { document.querySelectorAll('.app-view').forEach(el=>el.hidden=true); document.querySelector(`#${view}-view`).hidden=false; document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); window.scrollTo({top:0,behavior:'smooth'}); }
function showCustomer(customer) { const labels=[['会社名称','company'],['顧客タイプ','type'],['住所','address'],['部署','department'],['連絡担当者','contact'],['電話','phone'],['メール','email'],['主な取扱商品','products'],['備考','notes']]; document.querySelector('#customer-detail-title').textContent=customer.company;document.querySelector('#customer-detail-number').textContent=`顧客番号：${customer.id}`;document.querySelector('#customer-detail-status').innerHTML=badge(customer.status);document.querySelector('#customer-profile').innerHTML=labels.map(([l,k])=>`<div class="profile-item ${k==='notes'?'wide':''}"><dt>${l}</dt><dd>${customer[k]}</dd></div>`).join(''); const qs=quotations.filter(q=>q.customerId===customer.id);document.querySelector('#customer-quote-body').innerHTML=qs.length?qs.map(q=>{const p=byCode(q.productCode);return `<tr><td>${q.no}</td><td>${formatDate(q.date)}</td><td>${p.name}</td><td>${q.qty}</td><td>${money(q.price)}</td><td>${money(q.qty*q.price)}</td><td>${badge(q.status)}</td></tr>`}).join(''):'<tr><td colspan="7">見積履歴はありません。</td></tr>'; const customerOrders=orders.filter(o=>o.customerId===customer.id);document.querySelector('#customer-order-body').innerHTML=customerOrders.length?customerOrders.map(o=>`<tr><td>${o.no}</td><td>${formatDate(o.date)}</td><td>${byCode(o.productCode).name}</td><td>${o.qty}</td><td>${money(o.qty*o.price)}</td><td>${badge(o.status)}</td></tr>`).join(''):'<tr><td colspan="6">受注履歴はありません。</td></tr>'; document.querySelector('#follow-up-list').innerHTML=customer.followUps.map(f=>`<article class="follow-up"><div class="follow-up-top"><span class="follow-up-date">${f.date}</span><span class="contact-method">${f.method} ｜ 営業担当：${f.owner}</span></div><p><strong>連絡内容：</strong>${f.content}</p><p><strong>お客様の反応：</strong>${f.feedback}</p><div class="follow-up-meta"><span>次回連絡日：<b>${f.nextDate}</b></span><span>次のアクション：<b>${f.action}</b></span></div></article>`).join(''); document.querySelector('#create-quote-for-customer').dataset.customerId=customer.id; showView('customer-detail'); }
function showProduct(code) { const p=byCode(code); const labels=[['商品コード','code'],['商品名','name'],['商品カテゴリー','category'],['原材料','ingredients'],['内容量','weight'],['荷姿','packing'],['ケース入数','case'],['賞味期限','expiry'],['保存方法','storage'],['標準単価','price'],['商品説明','description'],['備考','notes']]; document.querySelector('#product-profile').hidden=false;document.querySelector('#product-spec-message').hidden=true;document.querySelector('#product-profile').innerHTML=labels.map(([l,k])=>`<div class="profile-item ${(k==='description'||k==='notes')?'wide':''}"><dt>${l}</dt><dd>${k==='price'?money(p[k]):p[k]}</dd></div>`).join(''); }
function nextNumber(prefix, collection) { const year='2026'; const highest=collection.reduce((max,item)=>Math.max(max,Number(item.no.split('-').pop())||0),0); return `${prefix}-${year}-${String(highest+1).padStart(4,'0')}`; }
function populateSelects(prefix, customerId='', productCode='') { const customer=document.querySelector(`#${prefix}-customer`),product=document.querySelector(`#${prefix}-product`);customer.innerHTML='<option value="">顧客を選択</option>'+customers.map(c=>`<option value="${c.id}">${c.company}</option>`).join('');product.innerHTML='<option value="">商品を選択</option>'+products.map(p=>`<option value="${p.code}">${p.name}</option>`).join('');customer.value=customerId;product.value=productCode; }
function updateTotal(prefix) { const qty=Number(document.querySelector(`#${prefix}-quantity`).value)||0,price=Number(document.querySelector(`#${prefix}-price`).value)||0;document.querySelector(`#${prefix}-total`).textContent=money(qty*price); }
function populateQuoteForm(customerId='') { populateSelects('quote',customerId);document.querySelector('#quote-number').value=nextNumber('Q',quotations);document.querySelector('#quote-date').value=currentDate();document.querySelector('#quote-quantity').value=1;document.querySelector('#quote-price').value='';updateTotal('quote'); }
function openQuoteForm(customerId='') { showView('quotations');document.querySelector('#quote-form-card').hidden=false;populateQuoteForm(customerId); }
function openOrderForm(quotation) { showView('orders');document.querySelector('#order-form-card').hidden=false;populateSelects('order',quotation?.customerId,quotation?.productCode);document.querySelector('#order-number').value=nextNumber('O',orders);document.querySelector('#order-date').value=currentDate();document.querySelector('#order-quantity').value=quotation?.qty || 1;document.querySelector('#order-price').value=quotation?.price || '';document.querySelector('#order-delivery-date').value='';document.querySelector('#order-status').value='受注';document.querySelector('#order-quotation-no').value=quotation?.no || '';document.querySelector('#order-notes').value=quotation?.notes || '';updateTotal('order'); }
function createOrderFromQuotation(quotation) { if (quotation.status !== '受注' || orders.some(order => order.quotationNo === quotation.no)) return; const order={no:nextNumber('O',orders),date:currentDate(),customerId:quotation.customerId,productCode:quotation.productCode,qty:quotation.qty,price:quotation.price,deliveryDate:'',notes:quotation.notes,status:'受注',quotationNo:quotation.no};orders=[order,...orders];renderOrders();renderQuotations();showView('orders'); }
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();showView('customers')});
document.querySelector('#customer-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();renderCustomers(customers.filter(c=>[c.id,c.company,c.contact].join(' ').toLowerCase().includes(q)))});
document.querySelector('#product-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();renderProducts(products.filter(p=>[p.code,p.name,p.category].join(' ').toLowerCase().includes(q)))});
document.querySelector('#quotation-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();renderQuotations(quotations.filter(x=>[x.no,byId(x.customerId).company,byCode(x.productCode).name].join(' ').toLowerCase().includes(q)))});
document.querySelector('#order-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();renderOrders(orders.filter(x=>[x.no,byId(x.customerId).company,byCode(x.productCode).name,x.quotationNo].join(' ').toLowerCase().includes(q)))});
document.querySelector('#customer-table-body').addEventListener('click',e=>{const b=e.target.closest('[data-customer-id]');if(b)showCustomer(byId(b.dataset.customerId))});document.querySelector('#back-to-customers').addEventListener('click',()=>showView('customers'));
document.querySelector('#product-table-body').addEventListener('click',e=>{const row=e.target.closest('[data-product-code]');if(row)showProduct(row.dataset.productCode)});document.querySelector('#product-table-body').addEventListener('keydown',e=>{if(e.key==='Enter')showProduct(e.target.dataset.productCode)});
document.querySelector('#show-quote-form').addEventListener('click',()=>openQuoteForm());document.querySelector('#create-quote-for-customer').addEventListener('click',e=>openQuoteForm(e.currentTarget.dataset.customerId));document.querySelector('#cancel-quote-form').addEventListener('click',()=>document.querySelector('#quote-form-card').hidden=true);
document.querySelector('#show-order-form').addEventListener('click',()=>openOrderForm());document.querySelector('#cancel-order-form').addEventListener('click',()=>document.querySelector('#order-form-card').hidden=true);
document.querySelector('#quotation-table-body').addEventListener('click',e=>{const button=e.target.closest('[data-quotation-no]');if(button){const quotation=quotations.find(q=>q.no===button.dataset.quotationNo);if(quotation)createOrderFromQuotation(quotation);}});
['quote','order'].forEach(prefix=>{document.querySelector(`#${prefix}-quantity`).addEventListener('input',()=>updateTotal(prefix));document.querySelector(`#${prefix}-price`).addEventListener('input',()=>updateTotal(prefix));document.querySelector(`#${prefix}-product`).addEventListener('change',e=>{const p=byCode(e.target.value);if(p){document.querySelector(`#${prefix}-price`).value=p.price;updateTotal(prefix);}});});
document.querySelector('#quote-form').addEventListener('submit',e=>{e.preventDefault();const q={no:document.querySelector('#quote-number').value.trim(),date:document.querySelector('#quote-date').value,customerId:document.querySelector('#quote-customer').value,productCode:document.querySelector('#quote-product').value,qty:Number(document.querySelector('#quote-quantity').value),price:Number(document.querySelector('#quote-price').value),notes:document.querySelector('#quote-notes').value.trim(),status:document.querySelector('#quote-status').value};quotations=[q,...quotations];renderQuotations();document.querySelector('#quote-form-card').hidden=true;e.target.reset();});
document.querySelector('#order-form').addEventListener('submit',e=>{e.preventDefault();const quotationNo=document.querySelector('#order-quotation-no').value;if(quotationNo&&orders.some(o=>o.quotationNo===quotationNo)){return;}const o={no:document.querySelector('#order-number').value.trim(),date:document.querySelector('#order-date').value,customerId:document.querySelector('#order-customer').value,productCode:document.querySelector('#order-product').value,qty:Number(document.querySelector('#order-quantity').value),price:Number(document.querySelector('#order-price').value),deliveryDate:document.querySelector('#order-delivery-date').value,notes:document.querySelector('#order-notes').value.trim(),status:document.querySelector('#order-status').value,quotationNo};orders=[o,...orders];renderOrders();renderQuotations();document.querySelector('#order-form-card').hidden=true;e.target.reset();});
renderCustomers();renderProducts();renderQuotations();renderOrders();showView('customers');
